# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'composer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/icon_dark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #3c3c3c;")
        self.centralwidget.setObjectName("centralwidget")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.label_14.setStyleSheet("background-color: #191919;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.sceneView = QtWidgets.QGraphicsView(self.centralwidget)
        self.sceneView.setGeometry(QtCore.QRect(20, 50, 500, 500))
        self.sceneView.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.sceneView.setSceneRect(QtCore.QRectF(0.0, 0.0, 500.0, 500.0))
        self.sceneView.setObjectName("sceneView")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(513, 50, 41, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.runDebugBtn = QtWidgets.QPushButton(self.centralwidget)
        self.runDebugBtn.setGeometry(QtCore.QRect(370, 10, 31, 21))
        self.runDebugBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #383838;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 2px;\n"
"    border-right-color: #191919;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.runDebugBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runDebugBtn.setIcon(icon1)
        self.runDebugBtn.setObjectName("runDebugBtn")
        self.stopDebugBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopDebugBtn.setGeometry(QtCore.QRect(400, 10, 31, 21))
        self.stopDebugBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #383838;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 2px;\n"
"    border-left-color: #191919;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.stopDebugBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopDebugBtn.setIcon(icon2)
        self.stopDebugBtn.setObjectName("stopDebugBtn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 520, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/img/img/icon_light.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(690, 519, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(550, 190, 241, 201))
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"   border: 2px solid #575757;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"    color: white;\n"
"    border: 2px solid transparent;\n"
"    background-color: #3c3c3c;\n"
"    padding: 4px\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background-color: #575757;\n"
"    border-right-color: rgb(85, 170, 255);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.transformTab = QtWidgets.QWidget()
        self.transformTab.setObjectName("transformTab")
        self.xPosSpin = QtWidgets.QDoubleSpinBox(self.transformTab)
        self.xPosSpin.setGeometry(QtCore.QRect(80, 60, 61, 21))
        self.xPosSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.xPosSpin.setMinimum(-1000.0)
        self.xPosSpin.setMaximum(1000.0)
        self.xPosSpin.setObjectName("xPosSpin")
        self.label = QtWidgets.QLabel(self.transformTab)
        self.label.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.label.setStyleSheet("color: white;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.transformTab)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 71, 21))
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.yPosSpin = QtWidgets.QDoubleSpinBox(self.transformTab)
        self.yPosSpin.setGeometry(QtCore.QRect(80, 100, 61, 21))
        self.yPosSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.yPosSpin.setMinimum(-1000.0)
        self.yPosSpin.setMaximum(1000.0)
        self.yPosSpin.setObjectName("yPosSpin")
        self.label_17 = QtWidgets.QLabel(self.transformTab)
        self.label_17.setGeometry(QtCore.QRect(40, 20, 31, 21))
        self.label_17.setStyleSheet("color: white;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.nameInput = QtWidgets.QLineEdit(self.transformTab)
        self.nameInput.setGeometry(QtCore.QRect(80, 20, 101, 20))
        self.nameInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.nameInput.setObjectName("nameInput")
        self.label.raise_()
        self.xPosSpin.raise_()
        self.label_2.raise_()
        self.yPosSpin.raise_()
        self.label_17.raise_()
        self.nameInput.raise_()
        self.tabWidget.addTab(self.transformTab, "")
        self.renderTab = QtWidgets.QWidget()
        self.renderTab.setObjectName("renderTab")
        self.layerSpin = QtWidgets.QSpinBox(self.renderTab)
        self.layerSpin.setGeometry(QtCore.QRect(80, 59, 42, 22))
        self.layerSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.layerSpin.setObjectName("layerSpin")
        self.label_8 = QtWidgets.QLabel(self.renderTab)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 41, 20))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.renderTab)
        self.label_9.setGeometry(QtCore.QRect(20, 140, 51, 20))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.scaleSpin = QtWidgets.QDoubleSpinBox(self.renderTab)
        self.scaleSpin.setGeometry(QtCore.QRect(80, 140, 62, 22))
        self.scaleSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.scaleSpin.setObjectName("scaleSpin")
        self.defaultFrameSpin = QtWidgets.QSpinBox(self.renderTab)
        self.defaultFrameSpin.setGeometry(QtCore.QRect(80, 99, 42, 22))
        self.defaultFrameSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.defaultFrameSpin.setObjectName("defaultFrameSpin")
        self.label_10 = QtWidgets.QLabel(self.renderTab)
        self.label_10.setGeometry(QtCore.QRect(20, 100, 41, 20))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.renderCheck = QtWidgets.QCheckBox(self.renderTab)
        self.renderCheck.setGeometry(QtCore.QRect(50, 20, 20, 21))
        self.renderCheck.setText("")
        self.renderCheck.setChecked(True)
        self.renderCheck.setObjectName("renderCheck")
        self.label_18 = QtWidgets.QLabel(self.renderTab)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 31, 20))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.renderTab)
        self.label_19.setGeometry(QtCore.QRect(90, 20, 31, 20))
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.flipXCheck = QtWidgets.QCheckBox(self.renderTab)
        self.flipXCheck.setGeometry(QtCore.QRect(120, 20, 21, 21))
        self.flipXCheck.setText("")
        self.flipXCheck.setObjectName("flipXCheck")
        self.label_18.raise_()
        self.layerSpin.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.scaleSpin.raise_()
        self.defaultFrameSpin.raise_()
        self.label_10.raise_()
        self.renderCheck.raise_()
        self.label_19.raise_()
        self.flipXCheck.raise_()
        self.tabWidget.addTab(self.renderTab, "")
        self.collisionTab = QtWidgets.QWidget()
        self.collisionTab.setObjectName("collisionTab")
        self.label_11 = QtWidgets.QLabel(self.collisionTab)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 51, 20))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.collisionCheck = QtWidgets.QCheckBox(self.collisionTab)
        self.collisionCheck.setGeometry(QtCore.QRect(76, 20, 20, 21))
        self.collisionCheck.setText("")
        self.collisionCheck.setObjectName("collisionCheck")
        self.label_12 = QtWidgets.QLabel(self.collisionTab)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 71, 21))
        self.label_12.setStyleSheet("color: white;")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.collisionTab)
        self.label_13.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.label_13.setStyleSheet("color: white;")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.xCollisionSpin = QtWidgets.QDoubleSpinBox(self.collisionTab)
        self.xCollisionSpin.setGeometry(QtCore.QRect(80, 60, 61, 21))
        self.xCollisionSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.xCollisionSpin.setMaximum(1000.0)
        self.xCollisionSpin.setObjectName("xCollisionSpin")
        self.yCollisionSpin = QtWidgets.QDoubleSpinBox(self.collisionTab)
        self.yCollisionSpin.setGeometry(QtCore.QRect(80, 100, 61, 21))
        self.yCollisionSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.yCollisionSpin.setMaximum(1000.0)
        self.yCollisionSpin.setObjectName("yCollisionSpin")
        self.tabWidget.addTab(self.collisionTab, "")
        self.scriptTab = QtWidgets.QWidget()
        self.scriptTab.setObjectName("scriptTab")
        self.label_15 = QtWidgets.QLabel(self.scriptTab)
        self.label_15.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.className = QtWidgets.QLineEdit(self.scriptTab)
        self.className.setGeometry(QtCore.QRect(80, 20, 121, 21))
        self.className.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.className.setObjectName("className")
        self.tabWidget.addTab(self.scriptTab, "")
        self.textTab = QtWidgets.QWidget()
        self.textTab.setObjectName("textTab")
        self.label_16 = QtWidgets.QLabel(self.textTab)
        self.label_16.setGeometry(QtCore.QRect(40, 20, 31, 21))
        self.label_16.setStyleSheet("color: white;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.textInput = QtWidgets.QLineEdit(self.textTab)
        self.textInput.setGeometry(QtCore.QRect(80, 20, 101, 20))
        self.textInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.textInput.setObjectName("textInput")
        self.tabWidget.addTab(self.textTab, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #676767;")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 390, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #676767;")
        self.label_6.setObjectName("label_6")
        self.soundList = QtWidgets.QListWidget(self.centralwidget)
        self.soundList.setGeometry(QtCore.QRect(550, 410, 231, 61))
        self.soundList.setStyleSheet("color: white;\n"
"border: 1px solid #676767;\n"
"background: #474747;\n"
"padding: 5px;")
        self.soundList.setObjectName("soundList")
        self.addSound = QtWidgets.QPushButton(self.centralwidget)
        self.addSound.setGeometry(QtCore.QRect(550, 480, 111, 23))
        self.addSound.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.addSound.setObjectName("addSound")
        self.delSound = QtWidgets.QPushButton(self.centralwidget)
        self.delSound.setGeometry(QtCore.QRect(670, 480, 111, 23))
        self.delSound.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.delSound.setObjectName("delSound")
        self.spriteList = QtWidgets.QListWidget(self.centralwidget)
        self.spriteList.setGeometry(QtCore.QRect(550, 70, 231, 101))
        self.spriteList.setStyleSheet("color: white;\n"
"border: 1px solid #676767;\n"
"background: #474747;\n"
"padding: 5px;")
        self.spriteList.setObjectName("spriteList")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(550, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #676767;")
        self.label_7.setObjectName("label_7")
        self.label_5.raise_()
        self.line.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_3.raise_()
        self.label_14.raise_()
        self.sceneView.raise_()
        self.runDebugBtn.raise_()
        self.stopDebugBtn.raise_()
        self.tabWidget.raise_()
        self.soundList.raise_()
        self.addSound.raise_()
        self.delSound.raise_()
        self.spriteList.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setStyleSheet("menubar {\n"
"color: rgb(62, 62, 62);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"menubar::item{\n"
"    background-color:transparent;\n"
"    padding:20 25 20 20px;\n"
"    border:4px solid transparent;\n"
"}\n"
"\n"
"menubar::item:selected{\n"
"    background-color: rgb(83, 91, 255);\n"
"    border-color:darkblue;\n"
"    background:rgba(100,100,100,150);\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuBuild = QtWidgets.QMenu(self.menubar)
        self.menuBuild.setObjectName("menuBuild")
        self.menuSprite = QtWidgets.QMenu(self.menubar)
        self.menuSprite.setObjectName("menuSprite")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 25, 25);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionAdd_Sprite = QtWidgets.QAction(MainWindow)
        self.actionAdd_Sprite.setObjectName("actionAdd_Sprite")
        self.actionAdd_Text = QtWidgets.QAction(MainWindow)
        self.actionAdd_Text.setObjectName("actionAdd_Text")
        self.actionBuild_Folder = QtWidgets.QAction(MainWindow)
        self.actionBuild_Folder.setObjectName("actionBuild_Folder")
        self.actionBuild_Binary = QtWidgets.QAction(MainWindow)
        self.actionBuild_Binary.setObjectName("actionBuild_Binary")
        self.actionNew_Sprite = QtWidgets.QAction(MainWindow)
        self.actionNew_Sprite.setObjectName("actionNew_Sprite")
        self.menuProject.addAction(self.actionNew)
        self.menuProject.addAction(self.actionOpen)
        self.menuProject.addAction(self.actionSave)
        self.menuProject.addAction(self.actionSaveAs)
        self.menuBuild.addAction(self.actionBuild_Folder)
        self.menuBuild.addAction(self.actionBuild_Binary)
        self.menuSprite.addAction(self.actionAdd_Sprite)
        self.menuSprite.addAction(self.actionAdd_Text)
        self.menuSprite.addAction(self.actionNew_Sprite)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuSprite.menuAction())
        self.menubar.addAction(self.menuBuild.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Composer"))
        self.label_5.setText(_translate("MainWindow", "Composer"))
        self.label.setText(_translate("MainWindow", "X 轴位置"))
        self.label_2.setText(_translate("MainWindow", "Y 轴位置"))
        self.label_17.setText(_translate("MainWindow", "名称"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transformTab), _translate("MainWindow", "基本"))
        self.label_8.setText(_translate("MainWindow", "所在层"))
        self.label_9.setText(_translate("MainWindow", "渲染缩放"))
        self.label_10.setText(_translate("MainWindow", "默认帧"))
        self.label_18.setText(_translate("MainWindow", "启用"))
        self.label_19.setText(_translate("MainWindow", "翻转"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.renderTab), _translate("MainWindow", "渲染"))
        self.label_11.setText(_translate("MainWindow", "启用碰撞"))
        self.label_12.setText(_translate("MainWindow", "Y 轴大小"))
        self.label_13.setText(_translate("MainWindow", "X 轴大小"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.collisionTab), _translate("MainWindow", "碰撞"))
        self.label_15.setText(_translate("MainWindow", "脚本类名"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scriptTab), _translate("MainWindow", "行为"))
        self.label_16.setText(_translate("MainWindow", "文本"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.textTab), _translate("MainWindow", "文字"))
        self.label_3.setText(_translate("MainWindow", "Inspector"))
        self.label_6.setText(_translate("MainWindow", "Sound"))
        self.addSound.setText(_translate("MainWindow", "添加"))
        self.delSound.setText(_translate("MainWindow", "删除"))
        self.label_7.setText(_translate("MainWindow", "Scene"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuBuild.setTitle(_translate("MainWindow", "Build"))
        self.menuSprite.setTitle(_translate("MainWindow", "Sprite"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSaveAs.setText(_translate("MainWindow", "SaveAs"))
        self.actionAdd_Sprite.setText(_translate("MainWindow", "Add Sprite"))
        self.actionAdd_Text.setText(_translate("MainWindow", "Add Text"))
        self.actionBuild_Folder.setText(_translate("MainWindow", "Build Folder"))
        self.actionBuild_Binary.setText(_translate("MainWindow", "Build Binary"))
        self.actionNew_Sprite.setText(_translate("MainWindow", "New Sprite"))
