# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/icon_dark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #3c3c3c;")
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 781, 571))
        self.tabs.setAutoFillBackground(False)
        self.tabs.setStyleSheet("QTabWidget::pane{}\n"
"\n"
"QTabBar::tab{\n"
"    color: white;\n"
"    border: 2px solid transparent;\n"
"    background-color: #282828;\n"
"    padding: 4px\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background-color: #3c3c3c;\n"
"    border-top-color: rgb(85, 170, 255);\n"
"}")
        self.tabs.setObjectName("tabs")
        self.spriteTab = QtWidgets.QWidget()
        self.spriteTab.setAutoFillBackground(False)
        self.spriteTab.setStyleSheet("color: rgb(71, 71, 71);")
        self.spriteTab.setObjectName("spriteTab")
        self.spriteView = QtWidgets.QGraphicsView(self.spriteTab)
        self.spriteView.setGeometry(QtCore.QRect(30, 10, 500, 500))
        self.spriteView.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.spriteView.setSceneRect(QtCore.QRectF(0.0, 0.0, 500.0, 500.0))
        self.spriteView.setObjectName("spriteView")
        self.label = QtWidgets.QLabel(self.spriteTab)
        self.label.setGeometry(QtCore.QRect(590, 180, 31, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.rowSpin = QtWidgets.QSpinBox(self.spriteTab)
        self.rowSpin.setGeometry(QtCore.QRect(670, 220, 42, 22))
        self.rowSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.rowSpin.setMinimum(0)
        self.rowSpin.setProperty("value", 0)
        self.rowSpin.setObjectName("rowSpin")
        self.label_2 = QtWidgets.QLabel(self.spriteTab)
        self.label_2.setGeometry(QtCore.QRect(590, 220, 51, 20))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.spriteTab)
        self.label_3.setGeometry(QtCore.QRect(590, 260, 51, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.colSpin = QtWidgets.QSpinBox(self.spriteTab)
        self.colSpin.setGeometry(QtCore.QRect(670, 260, 42, 22))
        self.colSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.colSpin.setMinimum(0)
        self.colSpin.setProperty("value", 0)
        self.colSpin.setObjectName("colSpin")
        self.sliceBtn = QtWidgets.QPushButton(self.spriteTab)
        self.sliceBtn.setGeometry(QtCore.QRect(590, 300, 151, 23))
        self.sliceBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.sliceBtn.setObjectName("sliceBtn")
        self.openImageBtn = QtWidgets.QPushButton(self.spriteTab)
        self.openImageBtn.setGeometry(QtCore.QRect(630, 180, 111, 23))
        self.openImageBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.openImageBtn.setObjectName("openImageBtn")
        self.label_4 = QtWidgets.QLabel(self.spriteTab)
        self.label_4.setGeometry(QtCore.QRect(660, 480, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/img/img/icon_light.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.spriteTab)
        self.label_5.setGeometry(QtCore.QRect(680, 479, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.spriteView.raise_()
        self.label.raise_()
        self.rowSpin.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.colSpin.raise_()
        self.sliceBtn.raise_()
        self.openImageBtn.raise_()
        self.label_4.raise_()
        self.tabs.addTab(self.spriteTab, "")
        self.controllerTab = QtWidgets.QWidget()
        self.controllerTab.setAutoFillBackground(False)
        self.controllerTab.setObjectName("controllerTab")
        self.triggerList = QtWidgets.QListWidget(self.controllerTab)
        self.triggerList.setGeometry(QtCore.QRect(20, 51, 231, 311))
        self.triggerList.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.triggerList.setObjectName("triggerList")
        self.animeList = QtWidgets.QListWidget(self.controllerTab)
        self.animeList.setGeometry(QtCore.QRect(280, 50, 231, 311))
        self.animeList.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.animeList.setObjectName("animeList")
        self.transitionList = QtWidgets.QListWidget(self.controllerTab)
        self.transitionList.setGeometry(QtCore.QRect(540, 50, 231, 311))
        self.transitionList.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.transitionList.setObjectName("transitionList")
        self.line = QtWidgets.QFrame(self.controllerTab)
        self.line.setGeometry(QtCore.QRect(245, 30, 41, 451))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.controllerTab)
        self.line_2.setGeometry(QtCore.QRect(510, 30, 31, 451))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_11 = QtWidgets.QLabel(self.controllerTab)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);s")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.controllerTab)
        self.label_12.setGeometry(QtCore.QRect(280, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);s")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.controllerTab)
        self.label_13.setGeometry(QtCore.QRect(540, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);s")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.triggerName = QtWidgets.QLineEdit(self.controllerTab)
        self.triggerName.setGeometry(QtCore.QRect(80, 380, 141, 21))
        self.triggerName.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.triggerName.setObjectName("triggerName")
        self.label_6 = QtWidgets.QLabel(self.controllerTab)
        self.label_6.setGeometry(QtCore.QRect(40, 380, 31, 21))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);s")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.addTriggerBtn = QtWidgets.QPushButton(self.controllerTab)
        self.addTriggerBtn.setGeometry(QtCore.QRect(50, 420, 71, 23))
        self.addTriggerBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.addTriggerBtn.setObjectName("addTriggerBtn")
        self.delTriggerBtn = QtWidgets.QPushButton(self.controllerTab)
        self.delTriggerBtn.setGeometry(QtCore.QRect(150, 420, 71, 23))
        self.delTriggerBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.delTriggerBtn.setObjectName("delTriggerBtn")
        self.animeName = QtWidgets.QLineEdit(self.controllerTab)
        self.animeName.setGeometry(QtCore.QRect(350, 379, 141, 21))
        self.animeName.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.animeName.setObjectName("animeName")
        self.label_7 = QtWidgets.QLabel(self.controllerTab)
        self.label_7.setGeometry(QtCore.QRect(310, 380, 31, 21))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);s")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.delAnimeBtn = QtWidgets.QPushButton(self.controllerTab)
        self.delAnimeBtn.setGeometry(QtCore.QRect(420, 480, 71, 23))
        self.delAnimeBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.delAnimeBtn.setObjectName("delAnimeBtn")
        self.addAnimeBtn = QtWidgets.QPushButton(self.controllerTab)
        self.addAnimeBtn.setGeometry(QtCore.QRect(320, 480, 71, 23))
        self.addAnimeBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.addAnimeBtn.setObjectName("addAnimeBtn")
        self.fromSpin = QtWidgets.QSpinBox(self.controllerTab)
        self.fromSpin.setGeometry(QtCore.QRect(350, 410, 42, 22))
        self.fromSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.fromSpin.setObjectName("fromSpin")
        self.toSpin = QtWidgets.QSpinBox(self.controllerTab)
        self.toSpin.setGeometry(QtCore.QRect(450, 410, 41, 22))
        self.toSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.toSpin.setObjectName("toSpin")
        self.label_8 = QtWidgets.QLabel(self.controllerTab)
        self.label_8.setGeometry(QtCore.QRect(300, 411, 41, 20))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.controllerTab)
        self.label_9.setGeometry(QtCore.QRect(400, 410, 41, 20))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.intervalSpin = QtWidgets.QDoubleSpinBox(self.controllerTab)
        self.intervalSpin.setGeometry(QtCore.QRect(430, 438, 61, 21))
        self.intervalSpin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"border: 0px solid transparent;")
        self.intervalSpin.setObjectName("intervalSpin")
        self.label_10 = QtWidgets.QLabel(self.controllerTab)
        self.label_10.setGeometry(QtCore.QRect(370, 440, 51, 20))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.fromCombo = QtWidgets.QComboBox(self.controllerTab)
        self.fromCombo.setGeometry(QtCore.QRect(610, 380, 151, 22))
        self.fromCombo.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);")
        self.fromCombo.setObjectName("fromCombo")
        self.label_15 = QtWidgets.QLabel(self.controllerTab)
        self.label_15.setGeometry(QtCore.QRect(550, 380, 51, 21))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);s")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.controllerTab)
        self.label_16.setGeometry(QtCore.QRect(550, 410, 51, 21))
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);s")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.toCombo = QtWidgets.QComboBox(self.controllerTab)
        self.toCombo.setGeometry(QtCore.QRect(610, 410, 151, 22))
        self.toCombo.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);")
        self.toCombo.setObjectName("toCombo")
        self.label_17 = QtWidgets.QLabel(self.controllerTab)
        self.label_17.setGeometry(QtCore.QRect(550, 440, 51, 21))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);s")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.triggerCombo = QtWidgets.QComboBox(self.controllerTab)
        self.triggerCombo.setGeometry(QtCore.QRect(610, 440, 151, 22))
        self.triggerCombo.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);")
        self.triggerCombo.setObjectName("triggerCombo")
        self.addTransitionBtn = QtWidgets.QPushButton(self.controllerTab)
        self.addTransitionBtn.setGeometry(QtCore.QRect(590, 480, 71, 23))
        self.addTransitionBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.addTransitionBtn.setObjectName("addTransitionBtn")
        self.delTransitionBtn = QtWidgets.QPushButton(self.controllerTab)
        self.delTransitionBtn.setGeometry(QtCore.QRect(690, 480, 71, 23))
        self.delTransitionBtn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(103, 103, 103);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(83, 83, 83);\n"
"}")
        self.delTransitionBtn.setObjectName("delTransitionBtn")
        self.line_2.raise_()
        self.line.raise_()
        self.triggerList.raise_()
        self.animeList.raise_()
        self.transitionList.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.triggerName.raise_()
        self.label_6.raise_()
        self.addTriggerBtn.raise_()
        self.delTriggerBtn.raise_()
        self.animeName.raise_()
        self.label_7.raise_()
        self.delAnimeBtn.raise_()
        self.addAnimeBtn.raise_()
        self.fromSpin.raise_()
        self.toSpin.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.intervalSpin.raise_()
        self.label_10.raise_()
        self.fromCombo.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.toCombo.raise_()
        self.label_17.raise_()
        self.triggerCombo.raise_()
        self.addTransitionBtn.raise_()
        self.delTransitionBtn.raise_()
        self.tabs.addTab(self.controllerTab, "")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(-17, -8, 821, 42))
        self.label_14.setStyleSheet("background-color: #191919;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_14.raise_()
        self.tabs.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 25, 25);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setStyleSheet("color: rgb(62, 62, 62);\n"
"background-color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionNewSprite = QtWidgets.QAction(MainWindow)
        self.actionNewSprite.setObjectName("actionNewSprite")
        self.actionOpenSprite = QtWidgets.QAction(MainWindow)
        self.actionOpenSprite.setObjectName("actionOpenSprite")
        self.actionSaveSprite = QtWidgets.QAction(MainWindow)
        self.actionSaveSprite.setObjectName("actionSaveSprite")
        self.actionSaveSpriteAs = QtWidgets.QAction(MainWindow)
        self.actionSaveSpriteAs.setObjectName("actionSaveSpriteAs")
        self.menuFile.addAction(self.actionNewSprite)
        self.menuFile.addAction(self.actionOpenSprite)
        self.menuFile.addAction(self.actionSaveSprite)
        self.menuFile.addAction(self.actionSaveSpriteAs)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Animator"))
        self.label.setText(_translate("MainWindow", "图片"))
        self.label_2.setText(_translate("MainWindow", "切分行数"))
        self.label_3.setText(_translate("MainWindow", "切分列数"))
        self.sliceBtn.setText(_translate("MainWindow", "切分"))
        self.openImageBtn.setText(_translate("MainWindow", "打开"))
        self.label_5.setText(_translate("MainWindow", "Animator"))
        self.tabs.setTabText(self.tabs.indexOf(self.spriteTab), _translate("MainWindow", "Sprite"))
        self.label_11.setText(_translate("MainWindow", "触发器"))
        self.label_12.setText(_translate("MainWindow", "动画片段"))
        self.label_13.setText(_translate("MainWindow", "状态转移"))
        self.label_6.setText(_translate("MainWindow", "名称"))
        self.addTriggerBtn.setText(_translate("MainWindow", "添加"))
        self.delTriggerBtn.setText(_translate("MainWindow", "删除"))
        self.label_7.setText(_translate("MainWindow", "名称"))
        self.delAnimeBtn.setText(_translate("MainWindow", "删除"))
        self.addAnimeBtn.setText(_translate("MainWindow", "添加"))
        self.label_8.setText(_translate("MainWindow", "起始帧"))
        self.label_9.setText(_translate("MainWindow", "结束帧"))
        self.label_10.setText(_translate("MainWindow", "帧间间隔"))
        self.label_15.setText(_translate("MainWindow", "起始状态"))
        self.label_16.setText(_translate("MainWindow", "目标状态"))
        self.label_17.setText(_translate("MainWindow", "触发器"))
        self.addTransitionBtn.setText(_translate("MainWindow", "添加"))
        self.delTransitionBtn.setText(_translate("MainWindow", "删除"))
        self.tabs.setTabText(self.tabs.indexOf(self.controllerTab), _translate("MainWindow", "控制器"))
        self.menuFile.setTitle(_translate("MainWindow", "Project"))
        self.actionNewSprite.setText(_translate("MainWindow", "New"))
        self.actionOpenSprite.setText(_translate("MainWindow", "Open"))
        self.actionSaveSprite.setText(_translate("MainWindow", "Save"))
        self.actionSaveSpriteAs.setText(_translate("MainWindow", "Save as"))
